/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Bridge;

/**
 *
 * @author Admin
 */
public class Bridge extends javax.swing.JFrame {

    /**
     * Creates new form Cubuk
     */
    public Bridge() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        O1 = new javax.swing.JLabel();
        O2 = new javax.swing.JLabel();
        O3 = new javax.swing.JLabel();
        O4 = new javax.swing.JLabel();
        O5 = new javax.swing.JLabel();
        O6 = new javax.swing.JLabel();
        O7 = new javax.swing.JLabel();
        O8 = new javax.swing.JLabel();
        O9 = new javax.swing.JLabel();
        O10 = new javax.swing.JLabel();
        D1 = new javax.swing.JLabel();
        D2 = new javax.swing.JLabel();
        D3 = new javax.swing.JLabel();
        D4 = new javax.swing.JLabel();
        D5 = new javax.swing.JLabel();
        D6 = new javax.swing.JLabel();
        D7 = new javax.swing.JLabel();
        D8 = new javax.swing.JLabel();
        V1 = new javax.swing.JLabel();
        V2 = new javax.swing.JLabel();
        V3 = new javax.swing.JLabel();
        V4 = new javax.swing.JLabel();
        V5 = new javax.swing.JLabel();
        V6 = new javax.swing.JLabel();
        V7 = new javax.swing.JLabel();
        V8 = new javax.swing.JLabel();
        V9 = new javax.swing.JLabel();
        U1 = new javax.swing.JLabel();
        U2 = new javax.swing.JLabel();
        U3 = new javax.swing.JLabel();
        U4 = new javax.swing.JLabel();
        U5 = new javax.swing.JLabel();
        U6 = new javax.swing.JLabel();
        U7 = new javax.swing.JLabel();
        U8 = new javax.swing.JLabel();
        U9 = new javax.swing.JLabel();
        U10 = new javax.swing.JLabel();
        KN220 = new javax.swing.JLabel();
        KN440 = new javax.swing.JLabel();
        KN1 = new javax.swing.JLabel();
        KN2 = new javax.swing.JLabel();
        KN3 = new javax.swing.JLabel();
        KN4 = new javax.swing.JLabel();
        KN5 = new javax.swing.JLabel();
        KN6 = new javax.swing.JLabel();
        KN7 = new javax.swing.JLabel();
        KN8 = new javax.swing.JLabel();
        KN9 = new javax.swing.JLabel();
        KN10 = new javax.swing.JLabel();
        KN11 = new javax.swing.JLabel();
        KN12 = new javax.swing.JLabel();
        KN13 = new javax.swing.JLabel();
        m25 = new javax.swing.JLabel();
        m25_1 = new javax.swing.JLabel();
        m25_2 = new javax.swing.JLabel();
        m25_3 = new javax.swing.JLabel();
        m25_4 = new javax.swing.JLabel();
        m25_5 = new javax.swing.JLabel();
        m25_6 = new javax.swing.JLabel();
        m25_7 = new javax.swing.JLabel();
        m25_8 = new javax.swing.JLabel();
        m25_9 = new javax.swing.JLabel();
        m25_10 = new javax.swing.JLabel();
        m185 = new javax.swing.JLabel();
        m1 = new javax.swing.JLabel();
        m2 = new javax.swing.JLabel();
        m3 = new javax.swing.JLabel();
        m4 = new javax.swing.JLabel();
        m5 = new javax.swing.JLabel();
        m6 = new javax.swing.JLabel();
        m7 = new javax.swing.JLabel();
        m8 = new javax.swing.JLabel();
        m9 = new javax.swing.JLabel();
        m10 = new javax.swing.JLabel();
        m11 = new javax.swing.JLabel();
        m12 = new javax.swing.JLabel();
        Text1 = new javax.swing.JTextField();
        Text2 = new javax.swing.JTextField();
        Text3 = new javax.swing.JTextField();
        Text4 = new javax.swing.JTextField();
        Text5 = new javax.swing.JTextField();
        Text6 = new javax.swing.JTextField();
        Text7 = new javax.swing.JTextField();
        Text8 = new javax.swing.JTextField();
        Text9 = new javax.swing.JTextField();
        Text10 = new javax.swing.JTextField();
        Text11 = new javax.swing.JTextField();
        Text12 = new javax.swing.JTextField();
        Text13 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        O1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        O1.setText("O1");
        getContentPane().add(O1, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 104, 50, 20));

        O2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        O2.setText("O2");
        getContentPane().add(O2, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 106, 50, 20));

        O3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        O3.setText("O3");
        getContentPane().add(O3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 106, 50, 20));

        O4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        O4.setText("O4");
        getContentPane().add(O4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 104, 50, 20));

        O5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        O5.setText("O5");
        getContentPane().add(O5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 104, 60, 20));

        O6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        O6.setText("O6");
        getContentPane().add(O6, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 100, 50, 30));

        O7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        O7.setText("O7");
        getContentPane().add(O7, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 100, 50, 30));

        O8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        O8.setText("O8");
        getContentPane().add(O8, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 100, 50, 30));

        O9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        O9.setText("O9");
        getContentPane().add(O9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 100, 50, 30));

        O10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        O10.setText("O10");
        getContentPane().add(O10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 100, 50, 30));

        D1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        D1.setText("D1");
        getContentPane().add(D1, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 150, 50, 20));

        D2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        D2.setText("D2");
        getContentPane().add(D2, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 160, 50, 20));

        D3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        D3.setText("D3");
        getContentPane().add(D3, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 180, 50, 20));

        D4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        D4.setText("D4");
        getContentPane().add(D4, new org.netbeans.lib.awtextra.AbsoluteConstraints(503, 200, 50, 20));

        D5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        D5.setText("D5");
        getContentPane().add(D5, new org.netbeans.lib.awtextra.AbsoluteConstraints(623, 180, 50, 20));

        D6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        D6.setText("D6");
        getContentPane().add(D6, new org.netbeans.lib.awtextra.AbsoluteConstraints(733, 200, 50, 20));

        D7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        D7.setText("D7");
        getContentPane().add(D7, new org.netbeans.lib.awtextra.AbsoluteConstraints(863, 180, 50, 20));

        D8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        D8.setText("D8");
        getContentPane().add(D8, new org.netbeans.lib.awtextra.AbsoluteConstraints(973, 150, 50, 20));

        V1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        V1.setText("V1");
        getContentPane().add(V1, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 140, 50, 20));

        V2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        V2.setText("V2");
        getContentPane().add(V2, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 170, 50, 20));

        V3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        V3.setText("V3");
        getContentPane().add(V3, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 190, 50, 20));

        V4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        V4.setText("V4");
        getContentPane().add(V4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 50, 20));

        V5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        V5.setText("V5");
        getContentPane().add(V5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 170, 50, 20));

        V6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        V6.setText("V6");
        getContentPane().add(V6, new org.netbeans.lib.awtextra.AbsoluteConstraints(673, 200, 50, 20));

        V7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        V7.setText("V7");
        getContentPane().add(V7, new org.netbeans.lib.awtextra.AbsoluteConstraints(793, 180, 50, 20));

        V8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        V8.setText("V8");
        getContentPane().add(V8, new org.netbeans.lib.awtextra.AbsoluteConstraints(913, 160, 50, 20));

        V9.setText("V9");
        getContentPane().add(V9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 140, 40, -1));

        U1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        U1.setText("U1");
        getContentPane().add(U1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 150, 50, 20));

        U2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        U2.setText("U2");
        getContentPane().add(U2, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 200, 50, 20));

        U3.setText("U3");
        getContentPane().add(U3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 224, 50, 20));

        U4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        U4.setText("U4");
        getContentPane().add(U4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 60, 30));

        U5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        U5.setText("U5");
        getContentPane().add(U5, new org.netbeans.lib.awtextra.AbsoluteConstraints(503, 274, 60, 20));

        U6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        U6.setText("U6");
        getContentPane().add(U6, new org.netbeans.lib.awtextra.AbsoluteConstraints(633, 270, 60, 30));

        U7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        U7.setText("U7");
        getContentPane().add(U7, new org.netbeans.lib.awtextra.AbsoluteConstraints(736, 270, 60, 30));

        U8.setText("U8");
        getContentPane().add(U8, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 250, 40, 20));

        U9.setText("U9");
        getContentPane().add(U9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 200, 50, 20));

        U10.setText("U10");
        getContentPane().add(U10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 160, 40, 20));

        KN220.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        KN220.setText("220");
        getContentPane().add(KN220, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 30, 30));

        KN440.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        KN440.setText("440");
        getContentPane().add(KN440, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 230, 30, 20));

        KN1.setText("KN");
        getContentPane().add(KN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, 20));

        KN2.setText("KN");
        getContentPane().add(KN2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, -1, 20));

        KN3.setText("KN");
        getContentPane().add(KN3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, -1, 20));

        KN4.setText("KN");
        getContentPane().add(KN4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, -1, 20));

        KN5.setText("KN");
        getContentPane().add(KN5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, -1, 20));

        KN6.setText("KN");
        getContentPane().add(KN6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, -1, 20));

        KN7.setText("KN");
        getContentPane().add(KN7, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 40, -1, 20));

        KN8.setText("KN");
        getContentPane().add(KN8, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 40, -1, 20));

        KN9.setText("KN");
        getContentPane().add(KN9, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 40, -1, 20));

        KN10.setText("KN");
        getContentPane().add(KN10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 40, -1, 20));

        KN11.setText("KN");
        getContentPane().add(KN11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 40, -1, 20));

        KN12.setText("KN");
        getContentPane().add(KN12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 20, 30));

        KN13.setText("KN");
        getContentPane().add(KN13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 230, 20, 20));

        m25.setText("25");
        getContentPane().add(m25, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, -1, -1));

        m25_1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        m25_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        m25_1.setText("13,9");
        getContentPane().add(m25_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 255, 30, 20));

        m25_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        m25_2.setText("2,5");
        getContentPane().add(m25_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 310, 30, 20));

        m25_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        m25_3.setText("2,5");
        getContentPane().add(m25_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 30, 20));

        m25_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        m25_4.setText("2,5");
        getContentPane().add(m25_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, 30, 20));

        m25_5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        m25_5.setText("2,5");
        getContentPane().add(m25_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(525, 310, 20, 20));

        m25_6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        m25_6.setText("2,5");
        getContentPane().add(m25_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 310, 20, 20));

        m25_7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        m25_7.setText("2,5");
        getContentPane().add(m25_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(745, 310, 30, 20));

        m25_8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        m25_8.setText("2,5");
        getContentPane().add(m25_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 310, 30, 20));

        m25_9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        m25_9.setText("2,5");
        getContentPane().add(m25_9, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 310, 30, 20));

        m25_10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        m25_10.setText("2,5");
        getContentPane().add(m25_10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 310, 30, 20));

        m185.setText("o");
        m185.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(m185, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 10, 20));

        m1.setText("m");
        getContentPane().add(m1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 360, -1, -1));

        m2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        m2.setText("m");
        getContentPane().add(m2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 20, 20));

        m3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        m3.setText("m");
        getContentPane().add(m3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 20, 20));

        m4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        m4.setText("m");
        getContentPane().add(m4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 20, 20));

        m5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        m5.setText("m");
        getContentPane().add(m5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, 20, 20));

        m6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        m6.setText("m");
        getContentPane().add(m6, new org.netbeans.lib.awtextra.AbsoluteConstraints(549, 310, 20, 20));

        m7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        m7.setText("m");
        getContentPane().add(m7, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 310, 20, 20));

        m8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        m8.setText("m");
        getContentPane().add(m8, new org.netbeans.lib.awtextra.AbsoluteConstraints(779, 310, 20, 20));

        m9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        m9.setText("m");
        getContentPane().add(m9, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 310, 20, 20));

        m10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        m10.setText("m");
        getContentPane().add(m10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 310, 20, 20));

        m11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        m11.setText("m");
        getContentPane().add(m11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 310, 20, 20));

        m12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        m12.setText("m");
        getContentPane().add(m12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 190, 10, -1));

        Text1.setBackground(new java.awt.Color(255, 255, 0));
        Text1.setText("10");
        getContentPane().add(Text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 40, 40, -1));

        Text2.setBackground(new java.awt.Color(255, 255, 0));
        Text2.setText("20");
        getContentPane().add(Text2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 40, -1));

        Text3.setBackground(new java.awt.Color(255, 255, 0));
        Text3.setText("30");
        getContentPane().add(Text3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 40, -1));

        Text4.setBackground(new java.awt.Color(255, 255, 0));
        Text4.setText("40");
        getContentPane().add(Text4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 40, -1));

        Text5.setBackground(new java.awt.Color(255, 255, 0));
        Text5.setText("50");
        getContentPane().add(Text5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, 40, -1));

        Text6.setBackground(new java.awt.Color(255, 255, 0));
        Text6.setText("60");
        getContentPane().add(Text6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, 40, -1));

        Text7.setBackground(new java.awt.Color(255, 255, 0));
        Text7.setText("70");
        getContentPane().add(Text7, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 40, 40, -1));

        Text8.setBackground(new java.awt.Color(255, 255, 0));
        Text8.setText("80");
        getContentPane().add(Text8, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 40, 40, -1));

        Text9.setBackground(new java.awt.Color(255, 255, 0));
        Text9.setText("90");
        getContentPane().add(Text9, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 40, 40, -1));

        Text10.setBackground(new java.awt.Color(255, 255, 0));
        Text10.setText("100");
        getContentPane().add(Text10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 40, 40, -1));

        Text11.setBackground(new java.awt.Color(255, 255, 0));
        Text11.setText("110");
        getContentPane().add(Text11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 40, 40, -1));

        Text12.setBackground(new java.awt.Color(255, 255, 0));
        Text12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Text12.setText("2,5");
        getContentPane().add(Text12, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 310, 40, -1));

        Text13.setBackground(new java.awt.Color(255, 255, 0));
        Text13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Text13.setText("1,85");
        getContentPane().add(Text13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 190, 30, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\3ef81d8e-1308-43fb-92f2-df3916769eba100.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bridge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bridge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bridge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bridge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bridge().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel D1;
    private javax.swing.JLabel D2;
    private javax.swing.JLabel D3;
    private javax.swing.JLabel D4;
    private javax.swing.JLabel D5;
    private javax.swing.JLabel D6;
    private javax.swing.JLabel D7;
    private javax.swing.JLabel D8;
    private javax.swing.JLabel KN1;
    private javax.swing.JLabel KN10;
    private javax.swing.JLabel KN11;
    private javax.swing.JLabel KN12;
    private javax.swing.JLabel KN13;
    private javax.swing.JLabel KN2;
    private javax.swing.JLabel KN220;
    private javax.swing.JLabel KN3;
    private javax.swing.JLabel KN4;
    private javax.swing.JLabel KN440;
    private javax.swing.JLabel KN5;
    private javax.swing.JLabel KN6;
    private javax.swing.JLabel KN7;
    private javax.swing.JLabel KN8;
    private javax.swing.JLabel KN9;
    private javax.swing.JLabel O1;
    private javax.swing.JLabel O10;
    private javax.swing.JLabel O2;
    private javax.swing.JLabel O3;
    private javax.swing.JLabel O4;
    private javax.swing.JLabel O5;
    private javax.swing.JLabel O6;
    private javax.swing.JLabel O7;
    private javax.swing.JLabel O8;
    private javax.swing.JLabel O9;
    private javax.swing.JTextField Text1;
    private javax.swing.JTextField Text10;
    private javax.swing.JTextField Text11;
    private javax.swing.JTextField Text12;
    private javax.swing.JTextField Text13;
    private javax.swing.JTextField Text2;
    private javax.swing.JTextField Text3;
    private javax.swing.JTextField Text4;
    private javax.swing.JTextField Text5;
    private javax.swing.JTextField Text6;
    private javax.swing.JTextField Text7;
    private javax.swing.JTextField Text8;
    private javax.swing.JTextField Text9;
    private javax.swing.JLabel U1;
    private javax.swing.JLabel U10;
    private javax.swing.JLabel U2;
    private javax.swing.JLabel U3;
    private javax.swing.JLabel U4;
    private javax.swing.JLabel U5;
    private javax.swing.JLabel U6;
    private javax.swing.JLabel U7;
    private javax.swing.JLabel U8;
    private javax.swing.JLabel U9;
    private javax.swing.JLabel V1;
    private javax.swing.JLabel V2;
    private javax.swing.JLabel V3;
    private javax.swing.JLabel V4;
    private javax.swing.JLabel V5;
    private javax.swing.JLabel V6;
    private javax.swing.JLabel V7;
    private javax.swing.JLabel V8;
    private javax.swing.JLabel V9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel m1;
    private javax.swing.JLabel m10;
    private javax.swing.JLabel m11;
    private javax.swing.JLabel m12;
    private javax.swing.JLabel m185;
    private javax.swing.JLabel m2;
    private javax.swing.JLabel m25;
    private javax.swing.JLabel m25_1;
    private javax.swing.JLabel m25_10;
    private javax.swing.JLabel m25_2;
    private javax.swing.JLabel m25_3;
    private javax.swing.JLabel m25_4;
    private javax.swing.JLabel m25_5;
    private javax.swing.JLabel m25_6;
    private javax.swing.JLabel m25_7;
    private javax.swing.JLabel m25_8;
    private javax.swing.JLabel m25_9;
    private javax.swing.JLabel m3;
    private javax.swing.JLabel m4;
    private javax.swing.JLabel m5;
    private javax.swing.JLabel m6;
    private javax.swing.JLabel m7;
    private javax.swing.JLabel m8;
    private javax.swing.JLabel m9;
    // End of variables declaration//GEN-END:variables
}
